const murphy = require("murphytest");
const md5 = require("md5");
const fs = require("fs");
eval(murphy.load(__dirname,"../../trellinator-libs/Notification.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Card.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Comment.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Board.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Member.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/List.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Label.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/Checklist.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/CheckItem.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/TrelloApi.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/TestConnector.js"));
eval(murphy.load(__dirname,"../../trellinator-libs/IterableCollection.js"));
eval(murphy.load(__dirname,"../Globals.js"));
eval(murphy.load(__dirname,"./comment_added.js"));
eval(murphy.load(__dirname,"./archived_card.js"));
eval(murphy.load(__dirname,"./archived_split_card.js"));
eval(murphy.load(__dirname,"./bucket_label_added.js"));
eval(murphy.load(__dirname,"./split_label_added.js"));
TestConnector.test_base_dir   = __dirname;
TestConnector.live_key      = process.argv[2];
TestConnector.live_token    = process.argv[3];
var NoffsParameters = function(){};
NoffsParameters.trellinator_username = "trellinatordev";

checkOffArchivedCard(archived_card);
copyComment(comment_added);
checkOffSplittedCard(archived_split_card);
bucket(bucket_label_added);
split(split_label_added);
